### ISSUE TITLE
Move parts of testing infrastructure, cmake macros to xt-data?

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-xt-data#30]
The ``merger`` branch does not depend on ``dune-xt(-common)`` anymore. This means we cannot use the ``dune-xt`` CMake macros and the testing infrastructure. I duplicated some CMake stuff from dune-xt to be able to detect Boost here, use clang-format, etc. In addition, the old tests use gtest and the ``test/main.hxx`` from ``dune-xt``.

As ``dune-xt`` depends on ``dune-xt-data`` anyway, maybe we should move CMake macros (and the gtest library) that are need both in ``dune-xt-data`` and ``dune-xt`` to ``dune-xt-data`` to avoid code duplication?

**Comment by renefritze** [comment]
Moving the testing infrastructure is possible, I hadn't really considered that.
I've got some big unpushed and unfinished changes to the cmake stuff in dune-xt atm. I will not be able to work on this until after the pymor school ends October 13th.

**Comment by ftalbrecht** [comment]
I would not want to move this. The whole reason for `xt-data` is to be a separate (huge) repo that can be easily made optional, if one of us has the time to do so. Moving things we require in `xt` effectively means we need no `xt-data`.
