### ISSUE TITLE
Use std::filesystem instead of boost::filesystem

### ISSUE THREAD

**Issue by tobiasleibner** [dune-community/dune-xt-data#45]
I tried this in #44. Simply searching and replacing all uses of  ``boost::filesystem::{ofstream,ifstream}`` by ``std::{ofstream,ifstream}`` and then ``boost::filesystem`` with ``std::filesystem`` works, both in ``dune-xt-data ``and in ``dune-xt``. However, ``gcc-8`` requires linking [an additional library](https://gitlab.kitware.com/cmake/cmake/-/issues/17834) to use ``std::filesystem``. We could probably add some CMake magic to link that library for ``gcc-8``, but as ``boost::filesystem`` works fine I would rather wait until we require a minimum gcc version of 9 anyway and revive #44 then.

**Comment by renefritze** [comment]
Sounds good :+1:
